### ISSUE TITLE
AdminCenter cho EasyWeb

### ISSUE THREAD

**Issue by baotnq** [easywebhub/tasks#2]
Yêu cầu cơ bản:
- Sử dụng SemanticUI để thống nhất layout
- Thiết lập Push to Deploy 
- Chạy trên Linux , nên là `Singapore: Centos 7.2 x64: 512M RAM: 128.199.210.69`
- Sử dụng API của api.easywebhub.com 

Recommend:
- Sử dụng Aurelia hoặc Vue
- source code lưu tại https://github.com/easywebhub/easyadmincp

@gattadesmond  cung cấp layout chuẩn SemanticUI cho các bạn

**Comment by baotnq** [comment]
chuẩn bị trước thứ 2 tuần sau (31/10/16) để demo nghe

**Comment by baotnq** [comment]
@thanhtdvn
- tạo ra project riêng cho phần này https://github.com/easywebhub/easyadmincp 
- đọc thêm phần readme để cài đặt cho đúng

**Comment by thanhtdvn** [comment]
okie a.

**Comment by thanhtdvn** [comment]
Hiện tại sourcecode + sourcebuild của api.easywebhub.com cùng đặt trên repository https://github.com/easywebhub/BackendEasyWeb => khó triển khai push-to-deploy.

Em muốn chuyển tất cả sourcebuild ( api.easywebhub.com, easyadmincp,...) sang 1 repository https://github.com/easywebhub/deployments để tách rời code build và sourcecode, tiện cho việc triển khai push-to-deploy cũng như dev ( cái này bữa e có nói qua với anh á).

Anh xem có gì không ổn không nhé @baotnq

**Comment by baotnq** [comment]
@thanhtdvn OK em, nhưng sourcebuild này dành cho API services .Net đúng ko em,
còn phần WebAdmin dùng VueJS hoặc Aurelia thì để trên repo   easyadmincp riêng nghe

**Comment by thanhtdvn** [comment]
Tại vì nếu viết bằng Aurelia thì cũng phải tách source build ra khỏi repository chứa sourcecode của nó anh Bảo @baotnq , để nó không bị đụng source của nhau. 
Nên sourcecode của easyadmincp  thì để trong repository easyadmincp
Sau khi build thì đẩy source build lên branch easyadmincp trong repository deployments , để triển khai push-to-deploy qua server deploy.

**Comment by baotnq** [comment]
@thanhtdvn, Anh góp ý thêm cho việc tách source code ra repositories riêng và phần build ra repo riêng. 

> Mục đích quan trọng nhất của việc tách này, là để phân quyền theo repo và bảo mật source code sau này

. Còn nếu chỉ vì lý do đụng source của nhau, thì không đáng để tách và quản trị riêng rẽ như vậy nghe. 

P/S **task này tới đâu rồi em, đã có deployed URL chưa.**

**Comment by baotnq** [comment]
@thanhtdvn cập nhật thông tin để còn close task này nghe

**Comment by thanhtdvn** [comment]
Đã xong.

Tiếp tục tại task: https://github.com/easywebhub/tasks/issues/12#issuecomment-260244109
