### ISSUE TITLE
Handlebar, extend partial not work

### ISSUE THREAD

**Issue by baotnq** [easywebhub/tasks#20]
> repo  https://github.com/baotnq/mtfashion-v2
- build by EasyBuilder, but the output page , `/trang-chu` is not show with `{{#extend ` partial
-  file .md  https://github.com/baotnq/mtfashion-v2/blob/master/content/trang-chu.md
- layout https://github.com/baotnq/mtfashion-v2/blob/master/layout/shop-full-width.html
-  partial https://github.com/baotnq/mtfashion-v2/blob/master/layout/partial/default.html

@nemesisqp debug xem van de o day nghe, chu repo tuong tu chay duoc
 - draco https://github.com/easywebhub/draco
 - layout  https://github.com/easywebhub/draco/blob/master/layout/index.html
 - partial  https://github.com/easywebhub/draco/blob/master/layout/partial/default.html

**Comment by nemesisqp** [comment]
Do bị trùng helper, `extend` là helper `extend` của handlebar-layouts trùng với helper `extend` của assemble.
project draco's  handlebars-helper.js `line:9` đã custom load helper exclude `extend` trong `object` helper
```
['array', 'code', 'collection', 'comparison', 'date', 'fs', 'html', 'i18n', 'inflection', 'logging', 'markdown', 'match', 'math', 'misc', 'number', 'path', 'string', 'url'].forEach(function(name) {
        Helpers[name]({
        handlebars: Handlebars
        });
    });
```

project mtfashion-v2's  handlebars-helper.js `line:9`  (load all assemble helpers)
```
Helpers({handlebars: Handlebars});
```

sửa lại như bên draco sẽ chạy như bt

**Comment by baotnq** [comment]
test OK
