### ISSUE TITLE
traning người mới về quy định của team

### ISSUE THREAD

**Issue by tungptvn** [easywebhub/tasks#24]
> dựa theo buổi họp team ngày (1/12)

**Comment by baotnq** [comment]
very good @tungptvn , và bổ sung các nội dung em sẽ thực hiện vào phần mô tả nghe, để trống vậy kì lắm

**Comment by baotnq** [comment]
@gattadesmond @vvthinh @thanhtdvn @thinnv  các bạn cũng thực hiện tương tự như @tungptvn  nghe
