### ISSUE TITLE
Cải thiện phần hiển thị Search trong EasyBuilder

### ISSUE THREAD

**Issue by baotnq** [easywebhub/tasks#29]
### Hiện tại
- danh sách file chỉ hiển thị file-name, không thân thiện với người dùng bằng `title`
- Phần search của EasyBuilder chỉ hỗ trợ tìm theo file-name

### Cải thiện
- Phần danh sách file hiển thị ở dạng 1 line với cấu trúc
  - `title` - current `category-name`

- Hiển thị tooltip khi hover, hiển thị 3 lines
  - line 1:  `title` đầy đủ
  - line 2: `filename.extention` đầy đủ
  - line 3:  `category` path đầy đủ, dạng  `cateA >> sub-cate-1 >> sub-cate-2`
 
- Tìm kiếm theo tiêu chí:
  - `title` hoặc `file-name`
  - tìm theo thuộc tính `field` trong file

**Comment by nemesisqp** [comment]
implemented in commit easywebhub/easyapp@b58fc009efec132367783370f734d07a5d104b52 and easywebhub/easyapp@64f204cb59ad9b87303b25ed50a20849b321adfe

**Comment by baotnq** [comment]
Test Filter: thấy như sau
 - github.com/easywebhub/medihub.git
   - gõ `Bui`, sau đó clear keyword, nhưng danh sách hiện ra không đủ như ban đầu
   - đã thử build lại, restart lại EasyBuilder, nhưng vẫn bị như trên

Điều chỉnh:
  - bỏ việc tìm kiếm theo `file-name`, chỉ tìm kiếm theo `title` thôi

**Comment by nemesisqp** [comment]
fixed + default to search title in  easywebhub/easyapp@5782784e4948b714c3c4557c59f3fe9c562f3734

**Comment by baotnq** [comment]
test lại thấy OK,  great done!!
