### ISSUE TITLE
Download & Synchronize websites of users among Desktops

### ISSUE THREAD

**Issue by baotnq** [easywebhub/tasks#50]
### Yêu cầu
- Cho phép download websites đã tạo vào máy khác
   - ưu tiên download source "master" trước
   - build "gh-pages" nếu làm lâu thì để sau

- Thảo luận: giao thức https hiện tại lộ user/pass trên url, nếu đổi sang dunng ssh thì có giải quyết được việc này không

**Comment by baotnq** [comment]
@nemesisqp theo như ý kiến của em thì việc username/pass trong `https://source.easywebhub.com` sẽ được encrypt và bảo mật khi send qua internet, nên giữ nguyên cách như hiện nay phải ko?

**Comment by nemesisqp** [comment]
flow của nó là khi gặp url kiểu https://user:pass@domain.com
thì 'user:pass' được base64 encode rồi gửi theo http request header
`Authorization: Basic + :base64EncodedData`
nên nếu sài ssl thì bên thứ 3 không bắt được
