### ISSUE TITLE
Setup Couchbase server 

### ISSUE THREAD

**Issue by baotnq** [easywebhub/tasks#56]
### VPS Info (test)
- IP address:  45.76.163.100 , account   root / 8.tT!g524Z1,m,S=
- Centos 7 64bit,  CPU 4 cores  , 4GB RAM, 90 SSD

### Todo
- Install couchbase server
   -  version:  4.5  Community 
   - guide::  https://developer.couchbase.com/documentation/server/4.5/install/install-linux.html
-  Try couchbase at link https://www.couchbase.com/get-started-developing-nosql
   - do to Step 3 Query Shell

- report what you've done with screenshots

**Comment by baotnq** [comment]
sử dụng putty để truy cập server:

- tài liệu https://vinahost.vn/ac/knowledgebase/84/Hng-dn-ssh-vao-server-bng-chng-trinh-Putty.html

**Comment by baotnq** [comment]
VPS này đang mua tại vultr.com, đây là thông tin để em search khi cần thiết. Lưu ý nghe
Có gì thì trao đổi, hoặc lưu các sceenshots trên đây luôn

**Comment by baotnq** [comment]
@leekirby6 việc này tiến triển tới đâu rồi em, còn gặp nhiều khó khăn không?

**Comment by leekirby6** [comment]
![1](https://cloud.githubusercontent.com/assets/10808157/23033064/5285f27c-f4a9-11e6-8225-ef6792b43701.PNG)
vps có vấn đề rồi anh, em không connect được nữa, tưởng máy em bị vấn đề về mạng nhưng tới giờ nó vẫn bị **network error**

**Comment by natuan62** [comment]
em đã config file **config.json** trong try-cb/ultis
update admin và password
edit **http://localhost:8091** thành **http://45.76.163.100:8091**
Còn phần kết nối tới vps trong trình duyệt thì em không rõ cách connect như thế nào? 
putty máy em tự dưng dính cái lỗi này, tìm trên gg, stackoverflow mà chưa sửa được
![1](https://cloud.githubusercontent.com/assets/10808157/23036044/e796898a-f4b3-11e6-8639-12956a277315.PNG)

**Comment by baotnq** [comment]
@leekirby6  cái này chắc do VPS bị gì đó không kết nối, anh đang gửi yêu cầu cho bên kia kiểm tra

**Comment by baotnq** [comment]
nếu đã config được `http://45.76.163.100:8091`, thì em chỉ cần vào link này trên browser, như firefox, chromes, đăng nhập và quản lý db này bình thường ah.
khi nào server chạy lại, anh báo nghe

**Comment by natuan62** [comment]
dạ

**Comment by natuan62** [comment]
putty login vào lại được rồi anh à !
![2](https://cloud.githubusercontent.com/assets/10808157/23058113/f4d7d5dc-f525-11e6-8318-d71803d2c87d.PNG)

**Comment by baotnq** [comment]
con server này hay bị lỗi nên anh xóa và tạo mới VPS mới,
```
OS: Centos 7 64bit
IP: 45.63.35.239
acc: root / $7Dk7Evk(,(1oFkA
```

Em cài đặt mới 1 lần nữa nghe. Lần này nếu được thì chụp step luôn

**Comment by baotnq** [comment]
sau khi setup xong, em cố gắng vọc Step 3 của https://www.couchbase.com/get-started-developing-nosql.
Phần
- Example Query , với câu lệnh bên dưới , phía trên phần hình nghe,
ví dụ
```
SELECT DISTINCT category, style
FROM `beer-sample`
WHERE type = "beer" AND 
      style LIKE "%Imperial%"
ORDER BY category, style;
```

**Comment by natuan62** [comment]
Phần config file config.json để chạy đường dẫn **45.63.35.239:8091** để truy cập Admin Console có lẽ em nhầm hay thiếu chỗ nào đó.
[couchbase server.docx](https://github.com/easywebhub/tasks/files/783847/couchbase.server.docx)
Còn phần truy vấn ở Step3 em cũng hiểu do trước có học môn CSDL SQL thấy cũng khá giống với noSQL :)

**Comment by baotnq** [comment]
@leekirby6 trong tai lieu cua em, anh chua thay phan nay, https://developer.couchbase.com/documentation/server/current/install/init-setup.html#topic12527 
em coi lai co lam buoc nay chua

**Comment by baotnq** [comment]
@thinnv em xem thu co ho tro duoc gi khong, dua theo kinh nghiem cai lan truoc cua em

**Comment by natuan62** [comment]
phần truy cập admin console sử dụng **http://ip adress:8091** em vẫn chưa làm được.
Để em xem kĩ lại sai mình sai ở đâu !

**Comment by thinnv** [comment]
Đang bị vướng chỗ nào vậy a @baotnq, theo e thấy
1. Ip:port  thì phải mở port 8091 để ở ngoài truy cập vào
2. Trong  try-cb muốn config username và pass thì phải cấu hình cho DocumentName password của nó. Nếu không thì bỏ password đi thì project try-cb connect được server

**Comment by natuan62** [comment]
Em vào được rồi, cảm ơn 2 anh @thinnv  @baotnq 
![12](https://cloud.githubusercontent.com/assets/10808157/23098947/a4efa64e-f68d-11e6-9fc4-6ec19f2fe381.PNG)

**Comment by baotnq** [comment]
@leekirby6 làm tốt lắm em!

- cập nhật lại tài liệu phần em điều chỉnh
- tiếp tục chạy cái sample try-cb, và cho phép anh truy cập từ ngoài qua IP:8080
- em vọc các query N1SQL để hiểu thêm (gửi anh pass `admin` bên trên

**Comment by natuan62** [comment]
[couchbase server_updated.docx](https://github.com/easywebhub/tasks/files/787895/couchbase.server_updated.docx)
Anh @thinnv giúp em cái với !
Cái thông báo **"No query nodes were found on this cluster, so N1QL querying is not possible."** thì phải sửa làm sao vậy anh ? Em tra google rồi nhưng không thấy nói cách giải quyết
![a](https://cloud.githubusercontent.com/assets/10808157/23131667/6bd8e4b6-f7bd-11e6-8be8-6bb500c55e93.PNG)

Tương tự với việc sử dụng command line trên centos
![b](https://cloud.githubusercontent.com/assets/10808157/23131651/5e19352e-f7bd-11e6-92f4-0511ca303900.PNG)

**Comment by baotnq** [comment]
"Your cluster was set up without a query service. If it's a multi-node service, remove a node and add it back with a query service. If you only have a single machine available (say your laptop) you'll need to tear down the instance and **restart (simplest way is to uninstall and reinstall) making sure to include a query service during set up. (In the UI the query service is included by default.)**

As Gerald mentions, we don't support adding services to already provisioned nodes -- they can only be added via node addition."

tham khảo https://forums.couchbase.com/t/want-to-turn-on-query-services-on-server-to-run-n1ql/11275/3

@leekirby6 anh thấy em đang cài 4.6, nhưng trong mô tả bên trên anh note là chỉ cần "version: 4.5 Community" thôi. Vậy em muốn uninstall và cài 4.5 không, hay để anh reset VPS về ban đầu cho nhanh và làm lại

**Comment by leekirby6** [comment]
Anh reset VPS về ban đầu giúp em luôn với ạ.

**Comment by natuan62** [comment]
Em đã gỡ 4.6 và đang cài lại 4.5 anh a

**Comment by baotnq** [comment]
anh lỡ reinstall nó ra mất rồi, em chịu khó cài lại nghe.

**Comment by natuan62** [comment]
Dạ tại hồi trưa em nhờ anh reset lại mà chưa thấy anh phản hồi nên em gỡ ra cài lại
Nói chung là xong hết rồi anh. Đang test mấy cái query mẫu xong lost connection =))
[couchbase server_updated.docx](https://github.com/easywebhub/tasks/files/789268/couchbase.server_updated.docx)


Để em cài lại sau :)

**Comment by natuan62** [comment]
Password có thay đổi gì không anh ? 
em dùng root|$7Dk7Evk(,(1oFkA thì bị access denied
![image](https://cloud.githubusercontent.com/assets/10808157/23153350/988c0dda-f83a-11e6-953e-43050c3d4e97.png)

**Comment by baotnq** [comment]
pass mới: r8K%S4uDLr2GuL@* 
OK em, sau đó tiếp tục vọc ở
 https://github.com/easywebhub/training-tasks/issues/1 nghe

**Comment by baotnq** [comment]
việc này tới đâu rồi em, gần xong chưa

**Comment by natuan62** [comment]
À, cái này xong từ hôm bữa mà anh bảo là reset lại cái vps.
Em nói là em cấu hình xong hết rồi xong anh bảo là **OK em, sau đó tiếp tục vọc ở
easywebhub/training-tasks#1 nghe**

**Comment by baotnq** [comment]
em cho anh thông tin để truy cập vào Couchbase thử nghe, account login. Nếu Couchbase truy cập được thì coi nhu xong phần này, làm tiếp theo tasks kia https://github.com/easywebhub/training-tasks/issues/1

**Comment by natuan62** [comment]
![capture](https://cloud.githubusercontent.com/assets/10808157/23353067/1ca47136-fcfd-11e6-8e04-2aca7bbf12f7.JPG)
nó lại bị dính cái lỗi này nữa rồi anh 
anh reset giúp em lại với

**Comment by baotnq** [comment]
cái VPS này chán quá, nên nếu vậy thì thôi, em cứ vọc các sample trong tasks kia nghe. 

Anh xóa cái VPS này cho rồi, sắp tới đưa em 1 vps mới của thằng khác để em luyện tập tiếp.

**Comment by baotnq** [comment]
task này hoàn thành
