### ISSUE TITLE
Lỗi khi chạy trên window 10

### ISSUE THREAD

**Issue by lehuunghi333** [easywebhub/tasks#59]
![screenshot 1](https://cloud.githubusercontent.com/assets/24203620/23055741/02d33a34-f51a-11e6-8825-1057fa453da3.png)

**Comment by baotnq** [comment]
@lehuunghi333 em cho biết thông tin môi trường, OS, 32 hay 64 bit nghe. Comment trên này luôn

**Comment by lehuunghi333** [comment]
Thông tin môi trường bị lỗi : Windows 10 64 bit

**Comment by baotnq** [comment]
dear @nemesisqp 

coi lại lỗi này nghe.

**Comment by nemesisqp** [comment]
Thêm code set name voi email trong commit easywebhub/easyapp@31e7d31fc399a1de3ee8231eb043efaed0644afd
Test lại thử xem

**Comment by baotnq** [comment]
@nemesisqp em build lại bản mới, gửi cho các bạn test nghe.
Chứ git pull về thì không còn ý nghĩa gì vì máy chưa có các cài đặt đó

**Comment by nemesisqp** [comment]
Cái này em set local trong app process thôi nên chạy lại là test được, set git global sẽ ảnh hường tới hoạt động của git bình thường ngoài app

**Comment by baotnq** [comment]
@nemesisqp ý anh là bên máy test ko có gì hết, và sau khi down bản build về thì bị lỗi. 
Giờ em  cần gửi lại bản build mới, fix lỗi trong backend.js, để down về lại, và test lại.
Chứ bạn đó ko biết cách, `git pull` hoặc là copy đè file `backend.js` mới đâu.

**Comment by nemesisqp** [comment]
Dev build link [EasyWebBuilder](https://github.com/easywebhub/easyapp/releases/download/v2.2-beta.5/EasyWebBuilder.zip)

**Comment by baotnq** [comment]
@lehuunghi333  em download link anh Phương vừa gửi bên trên, và test xem còn bị lỗi ko nghe.

**Comment by baotnq** [comment]
đã test ok
