### ISSUE TITLE
Triển khai API easyweb lên 107.175.56.236

### ISSUE THREAD

**Issue by baotnq** [easywebhub/tasks#7]
> Thông tin đã chỉnh trong https://github.com/easywebhub/tasks/blob/master/README.md

- Triển khai API easyweb đang có tại api.easywebhub.com lên VPS 107.175.56.236 (account trên Slack)
- Test các  api và thông báo anh để chuyển đổi domain api.easywebhub.com lên VPS mới này 
- Database vẫn giữ nguyên như cũ
- Áp dụng Push to Deploy trên VPS này luôn

@thanhtdvn  thực hiện cho quen tay nghe, có gì thì nhờ @thinnv  hỗ trợ.

**Comment by baotnq** [comment]
@thanhtdvn xong task này chưa nhỉ, xong thì cập nhật thông tin và label "Done" nghe

**Comment by thanhtdvn** [comment]
Đã xong. Update lại status
