### ISSUE TITLE
Dựng Metalsmith build microservice VPS 45.76.150.222 và chạy thử

### ISSUE THREAD

**Issue by tungptvn** [easywebhub/tasks#77]
>- Dựa theo #73 
> - Document [link](https://github.com/easywebhub/ms-site-builder/blob/master/README.md)

**Comment by baotnq** [comment]
@tungptvn  cái này thực hiện tới đâu rồi em. Anh tính để cho @leekirby6 cùng vọc cái này, em share account của VPS cũng như phối hợp với Tuấn cùng thực hiện nghe.
Nếu có trao đổi qua skype, hoặc trực tiếp thì cũng note lại trên này luôn nghe.

**Comment by tungptvn** [comment]
@baotnq em đang ưu tiên cái admincp còn nhiều vấn đề quá, @leekirby6 anh share VPS em câu hình chạy trước nhé.

**Comment by baotnq** [comment]
OK @tungptvn , cứ share thông tin trên skype cho @leekirby6 làm là được, cc anh vô trên skype nếu cần nghe.

**Comment by baotnq** [comment]
cái này tới đâu rồi các bạn, anh vừa tìm thấy 1 nhà cung cấp VPS khá ổn, dự kiến dùng lâu dài.
Nó đang cho free trial 60 ngày với VPS 1G RAM, 20SSD ổ cứng, đủ để chạy cái auto build này.

https://www.arubacloud.com/free-trial.aspx

@tungptvn hoặc @leekirby6  đăng ký thử 1 cái VPS để vọc nghe. Ngoài ra @tungptvn  chuyển các services trong `150.222` qua để ngưng chạy con này, hiện tại tốn tới 10$/ tháng lận.  Nếu ổn thì mình sẽ mở rộng ra sử dụng bên  aruba này nhiều hơn.

**Comment by baotnq** [comment]
các bạn xem comment cuối của anh chưa? 
@leekirby6  , thử đưa việc này cho bạn Tăng làm, em thấy sao?. Hiện tại chưa có github của tăng nên anh ko add vào đây được.

**Comment by natuan62** [comment]
@baotnq  cái vps aruba này em đăng ký từ hôm anh cmt luôn mà giờ vẫn chưa thấy nó gửi mã 
còn tăng em gửi github, gitlab hết cho anh rồi mà 
https://github.com/neteyemm
https://gitlab.com/neteyemm

> https://canhme.com/server/aruba-cloud-dung-thu-vps-mien-phi/
`Các bạn lưu ý dùng số Vinaphone hoặc Mobifone để nhận voucher, số Viettel không nhận được tin nhắn`
- hèn gì từ bữa tới giờ không thấy nó gửi

**Comment by baotnq** [comment]
@leekirby6 ku search ra canhme.com là hay lắm đó. :D

 em tạo task riêng cho mục aruba và sau đó phối hợp cùng @neteyemm  làm nghe, nhớ mô tả chi tiết thực hiện

**Comment by baotnq** [comment]
có thêm 1 VPS 2G RAM cho các bạn vọc nghe 
104.140.14.140   root   pass gửi qua skype

**Comment by baotnq** [comment]
@leekirby6 @tungptvn các bạn đã làm gì với task này chưa? hãy liệt kê công việc đã và sẽ làm nghe.

**Comment by natuan62** [comment]
@baotnq em tạo issue rồi assign cho bạn tăng thực hiện rồi anh. chứ em bận làm mockup quá chưa tham gia được.

**Comment by baotnq** [comment]
@leekirby6  ok em, cứ lo phần mockup đi nghe, còn @tungptvn  thì sao
