### ISSUE TITLE
Create Project Api MVC5 With Oracle DB

### ISSUE THREAD

**Issue by thinnv** [easywebhub/tasks#78]
- install Oracle Data Access Components (ODAC) with Oracle Developer Tools for Visual Studio [link](http://www.oracle.com/technetwork/topics/dotnet/utilsoft-086879.html)
  - Lúc cài đặt tạo luôn tnsname với host name, port và Service_name hoặc SID
- Tạo Project API MVC 5 và cài Oracle.ManagedDataAccess và Oracle.ManagedDataAccess.EntityFramework trong Nuget
- Tạo New item --> Data--> Ado.net Entity Data Model --> chọn thông tin
 
![image](https://cloud.githubusercontent.com/assets/6780364/24073497/cdbac1dc-0c2a-11e7-957d-8e34b9d63625.png)
Hoặc tham khảo link https://csharp.today/entity-framework-6-database-first-with-oracle/
cc @thanhtdvn

**Comment by baotnq** [comment]
@thinnv cái này tới đâu rồi em, commit source lên nghe
