### ISSUE TITLE
Review EasyWeb users' workflow

### ISSUE THREAD

**Issue by baotnq** [easywebhub/tasks#8]
> Users' workflow là các hoạt động, tính năng chính mà EasyWeb cung cấp cho người sử dụng, không phải là người xây dựng website

Thông tin mô tả ở wiki https://github.com/easywebhub/easyapp/wiki/EasyWeb-workflow, các bạn xem qua để nắm các thông tin này, hiểu về hoạt động tổng thể của EasyWeb

/cc @easywebhub/easyweb-core

**Comment by baotnq** [comment]
@easywebhub/easyweb-core  bạn nào đọc xong, thì comment bên dưới để xác nhận nghe.

**Comment by thinnv** [comment]
E đã đọc rồi nha a Bảo,
Em ko có ý kiến j kịch bản này. để hạn chế support chắc tài liệu mình phải nhiều và chất
